### ISSUE TITLE
FreeBSD renders wifibox devd conf irrelevant

### ISSUE THREAD

**Issue by MegaManSec** [pgj/freebsd-wifibox#120]
As of FreeBSD 14.0, `/etc/rc.suspend` will automatically call the respective rc-scripts when the system is suspending: https://github.com/freebsd/freebsd-src/commit/2cf8ef5910fd3754f8021f9c67fde6b9d9030f33

This means that `devd/wifibox.conf.sample` will become irrelevant. 

Some type of documentation update is probably in order here. I see no functional issues if a fbsd14 user still has that devd file, since `service wifibox suspend` will do nothing the second time it is run.

**Comment by pgj** [comment]
Oh, that is good news!  Thanks for reporting this.  I have not noticed this one because I am still using FreeBSD 13 (the oldest support release) on my notebook.

However, I disagree that the `devd(8)` would become immediately irrelevant due this.  That holds only for FreeBSD 14 and later.  We will still have to support FreeBSD 13 and keep this file (and all the associated bits) around until that is sunset officially.  For the implementation, this parts has to be made optional and deployed based on the OS major version.

**Comment by MegaManSec** [comment]
By "will become irrelevant" I mean will in the future when FreeBSD 13 becomes EOL. I agree with the rest of what you said about options and deployment based on the major version, but I did not want to build the solution myself;).

**Comment by pgj** [comment]
Hah, right, I missed the mind the future tense there :-)  Anyhow, no worries.  I can write the code for that and pass it over for you to review.  Usually I do not expect contributors to come to me with patches, but of course they are more than welcome to do so.

**Comment by MegaManSec** [comment]
LGTM
