### ISSUE TITLE
P2P? 

### ISSUE THREAD

**Issue by mkohanim** [pgj/freebsd-wifibox#34]
Hello,
The reason I am using wifibox is that FreeBSD driver for our network card does not yet support P2P or HOSTAP. The same card under Alpine does. So I was hoping to be able to do the same under wifibox alas it's a nogo.

Would you be adding support for P2P or HOSTAP? If not, would you please add the following commands in the image:
iwctl
wap-cli
apk

Thank you very much for your consideration.

With kind regards,
Michel

**Comment by pgj** [comment]
Hi @mkohanim: I am not sure I understand what you meant.

The Alpine Linux image that is provided for `wifibox` can run both `wpa_supplicant` and `hostapd` but only one of them at a time (for security hardening).  By default, `wpa_supplicant` is added for the image (and that is what you get when you install the binary package), but the `net/wifibox-alpine` port has a configuration option (`APP_HOSTAPD`) to use `hostapd` instead.  Note that all the configuration options of `wpa_supplicant` should work, hence the wireless card should be configured in AP mode even that way.   (I was able to do that some time in the past, at least.)

I guess you meant `wpa_cli` by `wap-cli`.  It is not needed in the image because there is a "Unix Domain Socket pass-through" implemented and `wpa_cli` (as well as `hostapd_cli`) can be used directly from the host.  The motivation is both to keep the VM image compact and to make the users forget about the VM completely: ideally, one should not interact with it in any way.

It also makes no sense to add the `apk` package manager to the image.  There is a read-only SquashFS-based root file system with some directories shared with the host (e.g. the `wpa_supplicant` and `hostapd` configuration files) and it is not meant to be extended with further packages.  This can only be done by changing the `net/wifibox-alpine` port (search for the `_PACKAGES` make variable in the `Makefile`) when building the image.  I am not familiar with `iwctl`.  There is [`iw`](https://wireless.wiki.kernel.org/en/users/documentation/iw) available in the VM maybe this can also help you to implement your goals.

**Comment by mkohanim** [comment]
@pgj , thank you so very much for the details and clarifications. The issue is that I need both hostapd and wpa_supplicant configurations at the same time. The reason is this: through our app, the customer will connects to hostapd (or P2P GO configuration) and provides his/her WiFi information which is stored in wpa_supplicant/wpa_supplicand.conf, rc.conf is update, the system reboots thus reverting to wpa_supplicant. Is it possible to have both?

With regard to using wpa_supplicant for AP mode, I tried P2P Go but I kept getting this error while the system was commissioning the p2p-dev:
failed setting mode 10 on p2p-dev.

With kind regards,
Michel

**Comment by pgj** [comment]
Sorry, I do not think I understand your use case.  How the customer can connect to `hostapd` when the Wifi information (credentials, you meant?) is stored in `wpa_supplicant.conf`?  The `hostapd` utility uses the `hostapd.conf` configuration file.  What is this `rc.conf` update?  Where does this happen and what is updated there exactly?  Why the system has to reboot?  Is this due to a crash?  Why to revert to `wpa_supplicant`?

How did you try to activate the P2P Go mode?  I would like to test this myself and reproduce the problem you reported in your comment.

**Comment by mkohanim** [comment]
@pgj ,
Thank you so very much for getting back. Apologies for not being clear. Here's more details:
On their mobile app (or computer, the customer connects to hostapd with some predetermined credentials (tied to their hardware). Now that they are connected to the hostapd, the app shows them a list of available WiFi networks to which the would like the hardware to connect (default is the network to which the mobile app was connected before connecting to hostpad). When the customer chooses the network, the app will ask for the password (PSK) for that network, and then posts it to a webserver on the hardware. This information (ssid and psk) is then used to configure wpa_supplicant and reboot. Once rebooted, wpa_supplicant will be back to normal (mode = 2 is gone) and will try to connect to the network that the customer chose. 

To answer your questions with regard to P2P issue, as I mentioned, I could not get P2P to work but, based on your input, got hostap to work [using these instructions](http://blog.hoxnox.com/gentoo/wifi-hotspot.html) . Currently, my only remaining issue is to have a server listening on the wifibox0 to get customer's input.

Thanks again.
