### ISSUE TITLE
Starting wifibox on HEAD crashes with vmm error

### ISSUE THREAD

**Issue by orbitz** [pgj/freebsd-wifibox#42]
I'm using

```
wifibox-alpine-20220712
wifibox-core-0.10.1
```

When I compile the latest kernel (`a1f28ec729f7491da8607e8eeaee1b0f547c60d0`), starting wifibox crashes.  The error is 

> panic: Lock (sx) vm mem_segs not locked @ /usr/src/sys/amd64/vmm/vmm.c:1188

Any ideas on this?  Seen it before?  Anything I can do to test it more?

**Comment by pgj** [comment]
I guess you mean a very recent version of FreeBSD 14-CURRENT by the "latest kernel".  Yes, I have also noticed this when I tried the latest release on a 14-CURRENT snapshot.  I have not had the time to investigate the situation but I am inclined to think that it has something to do with the base system itself.

I am not familiar with the `vmm` internals thus I have no clue about the exact cause of this error.  Other than it is related to the PCI pass-through functionality because it crashes when the guest tries to use the device.  Moving back to older and older versions of the base system might help to bisect the problem, which could be then linked to a specific change.  Then the issue could be reported to the authors.

**Comment by orbitz** [comment]
I created a ticket, you can track here if interested: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268744

**Comment by pgj** [comment]
Great, thank you very much.

**Comment by orbitz** [comment]
This is working on latest comments.

**Comment by pgj** [comment]
Thanks for the update @orbitz !
